import "./AboutView.css";

export default function AboutView() {
  return <div className="about-page">
    <header className="about-hero"><div><p className="eyebrow">Engineering overview</p><h1>From a churn model to a product people can interrogate.</h1></div><p>RetentionPulse turns a telecom churn model into an explainable, deployable decision-support application with a React interface, FastAPI microservices, SHAP explanations, tests, containers, and a public Render deployment.</p></header>
    <section className="proof-strip" aria-label="Project proof points"><div><strong>0.84</strong><span>ROC-AUC on held-out data</span></div><div><strong>3</strong><span>backend services behind one gateway</span></div><div><strong>100 / 1k</strong><span>batch / CSV row limits</span></div><div><strong>CI</strong><span>tests, linting, and production builds</span></div></section>
    <section className="about-section"><div className="section-label"><p className="eyebrow">System design</p><h2>One request path, clear ownership.</h2></div><div className="architecture-flow"><article><span>01</span><h3>React client</h3><p>Portfolio, drill-in, individual scoring, and CSV workflows in TypeScript.</p></article><i>→</i><article><span>02</span><h3>FastAPI gateway</h3><p>Customer catalogue, validation, CSV processing, structured errors, and API docs.</p></article><i>→</i><article><span>03</span><h3>Model services</h3><p>Dedicated LightGBM prediction and Tree SHAP explanation services.</p></article></div></section>
    <section className="about-section engineering-ledger"><div className="section-label"><p className="eyebrow">Implementation detail</p><h2>What was built around the model.</h2></div><dl><div><dt>Frontend</dt><dd>React, TypeScript, Vite, Framer Motion, Lucide</dd></div><div><dt>ML + explainability</dt><dd>LightGBM classifier, scikit-learn preprocessing, Tree SHAP</dd></div><div><dt>Runtime</dt><dd>FastAPI, async HTTP forwarding, shared connection client, Docker Compose</dd></div><div><dt>Reliability</dt><dd>Bounded model batches, row-level CSV errors, health checks, typed contracts</dd></div><div><dt>Verification</dt><dd>Pytest API/contract coverage, GitHub Actions lint/test/build pipeline</dd></div><div><dt>Deployment</dt><dd>Public frontend and service deployment on Render</dd></div></dl></section>
    <aside className="about-note"><p className="eyebrow">Design principle</p><p>Every individual prediction is paired with its strongest SHAP drivers, so a probability is never presented without an explanation of what moved it.</p></aside>
  </div>;
}
